/**
 * AI translations of the interface, written by scripts/i18n/translate.ts in the Quest Compendium repo (run it again
 * after adding English strings or a language). Used after the hand-written dictionaries; anything missing falls back
 * to English.
 */
export const GENERATED: Record<string, Record<string, string>> = {
  de: {
    "navGuides": "Guides",
    "navGetApp": "App holen",
    "language": "Sprache",
    "footerReport": "Guides werden mit KI-Hilfe erstellt. Fehler gefunden? {report} oder sag uns auf {discord} Bescheid. Spielnamen gehören ihren Eigentümern; diese Seite steht in keiner Verbindung zu Publishern.",
    "reportLink": "Hier melden",
    "reportTitle": "Fehler melden",
    "reportHint": "Was stimmt auf dieser Seite nicht? Nenne möglichst das Item, den Ort oder das Detail.",
    "reportEntry": "Welcher Eintrag ist falsch? (optional)",
    "reportEntryNone": "Nicht sicher oder die ganze Seite",
    "reportCorrect": "Was wäre richtig? (optional)",
    "reportCorrectHint": "z. B. liegt es unter dem Stein beim umgestürzten Baumstamm, nicht auf den westlichen Klippen",
    "reportSend": "Senden",
    "reportCancel": "Abbrechen",
    "reportThanks": "Danke! Wir prüfen das und bessern den Guide aus.",
    "reportError": "Konnte nicht gesendet werden. Versuch es später noch einmal oder melde es auf Discord.",
    "ctaTitle": "Kommst du in {game} nicht weiter?",
    "ctaBody": "Quest Compendium sieht deinen Bildschirm beim Spielen: Frag genau nach deiner Stelle und hab diesen Guide direkt neben dem Spiel offen.",
    "ctaButton": "Live-Hilfe beim Spielen holen",
    "gotIt": "Verstanden",
    "weakTo": "Schwach gegen",
    "onThisPage": "Auf dieser Seite",
    "relatedQuests": "Verwandte Quests",
    "notListed": "Nicht für dieses Gebiet gelistet: {list}.",
    "itemHow": "So geht's",
    "itemLockout": "Verpassbar, weil",
    "fights": "Wichtige Kämpfe",
    "fightEnemies": "Gegner",
    "fightThreats": "Gefahren",
    "fightWeak": "Schwächen & Resistenzen",
    "fightTactics": "Taktik",
    "fightRewards": "Belohnungen",
    "stealDrop": "Stehlen / Beute",
    "previous": "Zurück",
    "next": "Weiter",
    "dontMiss": "Nicht verpassen",
    "items": "Gegenstände",
    "secrets": "Geheimnisse",
    "enemies": "Gegner",
    "shops": "Händler & NPCs",
    "tips": "Tipps",
    "sourcesChecked": "Geprüfte Quellen: {list}",
    "guideOf": "{game} Guide",
    "checkedBadge": "Gegen Quellen geprüft",
    "allAreas": "Alle Gebiete in diesem Guide",
    "areaTitle": "{area} – {game} Guide: Items, Geheimnisse & Gegner | Quest Compendium",
    "areaDesc": "{game} {area} Guide: Items, Geheimnisse, Verpassbares und Gegnerschwächen.",
    "gameTitle": "{game} Guide & Komplettlösung | Quest Compendium",
    "gameDesc": "Gebiets-Guide für {game} mit Item-Checklisten, Geheimnissen, Verpassbarem und Gegnerschwächen.",
    "gameH1": "{game} Guide",
    "gameIntro": "Jedes Gebiet nach der Reihe, mit Checklisten für Items, Geheimnisse und Verpassbares. Deine Haken werden in diesem Browser gespeichert.",
    "statAreas": "Gebiete",
    "statThings": "Dinge zu finden",
    "statMissables": "Verpassbare markiert",
    "statChecked": "Seiten gegen Quellen geprüft",
    "statAreasOne": "Gebiet",
    "statThingsOne": "Fundstück",
    "statMissablesOne": "Verpassbares markiert",
    "statCheckedOne": "Seite mit Quellen abgeglichen",
    "statAll": "Alle",
    "continue": "Da weitermachen, wo du aufgehört hast",
    "indexTitle": "Game Guides & Komplettlösungen | Quest Compendium",
    "indexDesc": "Game-Guides mit Item-Checklisten, Geheimnissen, Verpassbarem und Gegnerschwächen – Gebiet für Gebiet.",
    "indexH1": "Game-Guides",
    "indexIntro": "Gebiet-für-Gebiet-Checklisten für Items, Geheimnisse, Verpassbares und Gegnerschwächen für {n} Spiele.",
    "indexMore": "Weitere Guides auf Englisch",
    "areasCount": "{n} Gebiete",
    "areasCountOne": "1 Gebiet",
    "none": "Die ersten Guides sind schon unterwegs.",
    "searchGames": "Spiele suchen…",
    "searchAreas": "Gebiete und Items suchen…",
    "sortAZ": "A–Z",
    "sortPopular": "Beliebteste",
    "sortNew": "Neueste",
    "popular": "Beliebt",
    "newGuides": "Neue Guides",
    "allGames": "Alle Spiele",
    "noMatches": "Keine Treffer für diese Suche.",
    "sortLabel": "Sortieren",
    "achTitle": "{game} Achievement-Guide & Roadmap: Alle {n} Erfolge | Quest Compendium",
    "achDesc": "Alle {n} Erfolge in {game}: So schaltest du sie frei, welche verpassbar sind und die Roadmap zu den 100 %.",
    "achH1": "{game} Achievement-Guide",
    "achIntro": "So schaltest du jeden Erfolg frei, welche du verpassen kannst und die beste Reihenfolge für alle. Hake sie einfach nach und nach ab.",
    "achLink": "Achievement-Guide & Roadmap",
    "achHere": "Erfolge in diesem Bereich",
    "searchAch": "Erfolge durchsuchen…",
    "imagesNote": "Spielbilder © ihre jeweiligen Eigentümer.",
    "achAll": "Alle Erfolge",
    "achMissable": "Verpassbar",
    "achRarity": "{n} % der Spieler",
    "achHidden": "Versteckter Erfolg: Tippen zum Aufdecken",
    "achInArea": "Ort: {area}",
    "rmTime": "Zeit bis 100 %",
    "rmDifficulty": "Schwierigkeit",
    "rmPlaythroughs": "Spieldurchgänge",
    "rmMissables": "Verpassbare Erfolge",
    "rmSteps": "Empfohlene Reihenfolge",
    "rmNoReturn": "Punkte ohne Wiederkehr"
  },
  es: {
    "navGuides": "Guías",
    "navGetApp": "Obtén la app",
    "language": "Idioma",
    "footerReport": "Las guías se escriben con ayuda de IA. ¿Viste un error? {report} o avísanos en {discord}. Los nombres de los juegos pertenecen a sus respectivos dueños; este sitio no está afiliado a ninguna distribuidora.",
    "reportLink": "Repórtalo aquí",
    "reportTitle": "Reportar un error",
    "reportHint": "¿Qué está mal en esta página? Si puedes, menciona el objeto, lugar o detalle.",
    "reportEntry": "¿Qué entrada es incorrecta? (opcional)",
    "reportEntryNone": "No sé con certeza, o es toda la página",
    "reportCorrect": "¿Qué es lo correcto? (opcional)",
    "reportCorrectHint": "ej. está bajo la roca junto al tronco caído, no en los acantilados del oeste",
    "reportSend": "Enviar",
    "reportCancel": "Cancelar",
    "reportThanks": "¡Gracias! Lo revisaremos y corregiremos la guía.",
    "reportError": "No se pudo enviar. Inténtalo de nuevo más tarde o avísanos por Discord.",
    "ctaTitle": "¿Te trabaste en {game}?",
    "ctaBody": "Quest Compendium ve tu pantalla mientras juegas: pregunta exactamente sobre dónde estás y mantén esta guía abierta junto a tu juego.",
    "ctaButton": "Recibe ayuda en vivo mientras juegas",
    "gotIt": "Entendido",
    "weakTo": "Débil contra",
    "onThisPage": "En esta página",
    "relatedQuests": "Misiones relacionadas",
    "notListed": "No listadas para esta zona: {list}.",
    "itemHow": "Cómo obtenerlo",
    "itemLockout": "Se puede perder si",
    "fights": "Combates clave",
    "fightEnemies": "Enemigos",
    "fightThreats": "Amenazas",
    "fightWeak": "Debilidades y resistencias",
    "fightTactics": "Tácticas",
    "fightRewards": "Recompensas",
    "stealDrop": "Robo / botín",
    "previous": "Anterior",
    "next": "Siguiente",
    "dontMiss": "Imperdibles",
    "items": "Objetos",
    "secrets": "Secretos",
    "enemies": "Enemigos",
    "shops": "Tiendas y personajes",
    "tips": "Consejos",
    "sourcesChecked": "Fuentes verificadas: {list}",
    "guideOf": "Guía de {game}",
    "checkedBadge": "Verificado con fuentes",
    "allAreas": "Todas las zonas de esta guía",
    "areaTitle": "{area} – Guía de {game}: Objetos, secretos y enemigos | Quest Compendium",
    "areaDesc": "Guía de {area} en {game}: objetos, secretos, coleccionables que se pueden perder y debilidades de enemigos.",
    "gameTitle": "Guía y walkthrough de {game} | Quest Compendium",
    "gameDesc": "Guía zona por zona de {game} con listas de objetos, secretos, cosas que puedes perderte y debilidades enemigas.",
    "gameH1": "Guía de {game}",
    "gameIntro": "Cada zona en orden, con listas de objetos, secretos y cosas que puedes perderte. Tu progreso se guarda en este navegador.",
    "statAreas": "zonas",
    "statThings": "cosas por encontrar",
    "statMissables": "imperdibles marcados",
    "statChecked": "páginas verificadas con fuentes",
    "statAreasOne": "área",
    "statThingsOne": "cosa por encontrar",
    "statMissablesOne": "marcado como perdible",
    "statCheckedOne": "página verificada con fuentes",
    "statAll": "Todo",
    "continue": "Continúa donde lo dejaste",
    "indexTitle": "Guías de juegos y walkthroughs | Quest Compendium",
    "indexDesc": "Guías de juegos con listas de objetos, secretos, cosas que puedes perderte y debilidades de enemigos, zona por zona.",
    "indexH1": "Guías de juegos",
    "indexIntro": "Listas zona por zona de objetos, secretos y cosas que puedes perderte, además de debilidades de enemigos, para {n} juegos.",
    "indexMore": "Más guías en inglés",
    "areasCount": "{n} zonas",
    "areasCountOne": "1 zona",
    "none": "Las primeras guías ya vienen en camino.",
    "searchGames": "Buscar juegos…",
    "searchAreas": "Buscar zonas y objetos…",
    "sortAZ": "A–Z",
    "sortPopular": "Más populares",
    "sortNew": "Más recientes",
    "popular": "Populares",
    "newGuides": "Nuevas guías",
    "allGames": "Todos los juegos",
    "noMatches": "No hay resultados para esa búsqueda.",
    "sortLabel": "Ordenar",
    "achTitle": "Guía de logros y roadmap de {game}: los {n} logros | Quest Compendium",
    "achDesc": "Los {n} logros de {game}: cómo desbloquearlos, cuáles son perdibles y el roadmap para el 100%.",
    "achH1": "Guía de logros de {game}",
    "achIntro": "Cómo desbloquear cada logro, cuáles puedes perderte y el mejor orden para conseguirlos todos. Márcalos sobre la marcha.",
    "achLink": "Guía de logros y roadmap",
    "achHere": "Logros aquí",
    "searchAch": "Buscar logros…",
    "imagesNote": "Las imágenes del juego son © de sus respectivos dueños.",
    "achAll": "Todos los logros",
    "achMissable": "Perdibles",
    "achRarity": "{n}% de los jugadores",
    "achHidden": "Logro secreto: toca para revelar",
    "achInArea": "Dónde: {area}",
    "rmTime": "Tiempo para el 100%",
    "rmDifficulty": "Dificultad",
    "rmPlaythroughs": "Partidas necesarias",
    "rmMissables": "Logros perdibles",
    "rmSteps": "Paso a paso recomendado",
    "rmNoReturn": "Puntos de no retorno"
  },
  fr: {
    "navGuides": "Guides",
    "navGetApp": "Télécharger l'app",
    "language": "Langue",
    "footerReport": "Les guides sont rédigés avec l'aide de l'IA. Une erreur ? {report}, ou prévenez-nous sur {discord}. Les noms de jeux appartiennent à leurs propriétaires ; ce site n'est affilié à aucun éditeur.",
    "reportLink": "Signalez-la ici",
    "reportTitle": "Signaler une erreur",
    "reportHint": "Qu'est-ce qui ne va pas sur cette page ? Précisez l'objet, le lieu ou le détail si possible.",
    "reportEntry": "Quelle entrée est incorrecte ? (facultatif)",
    "reportEntryNone": "Pas sûr(e), ou toute la page",
    "reportCorrect": "Quelle est la bonne info ? (facultatif)",
    "reportCorrectHint": "ex. c'est sous le rocher près du tronc couché, pas sur les falaises ouest",
    "reportSend": "Envoyer",
    "reportCancel": "Annuler",
    "reportThanks": "Merci ! On va vérifier ça et corriger le guide.",
    "reportError": "L'envoi a échoué. Réessayez plus tard ou prévenez-nous sur Discord.",
    "ctaTitle": "Bloqué dans {game} ?",
    "ctaBody": "Quest Compendium analyse votre écran pendant que vous jouez : posez vos questions selon l'endroit où vous êtes et gardez ce guide ouvert juste à côté de votre jeu.",
    "ctaButton": "Obtenir de l'aide en direct en jeu",
    "gotIt": "Compris",
    "weakTo": "Faiblesses",
    "onThisPage": "Sur cette page",
    "relatedQuests": "Quêtes associées",
    "notListed": "Non répertorié pour cette zone : {list}.",
    "itemHow": "Comment",
    "itemLockout": "Manquable car",
    "fights": "Combats clés",
    "fightEnemies": "Ennemis",
    "fightThreats": "Menaces",
    "fightWeak": "Faiblesses et résistances",
    "fightTactics": "Tactiques",
    "fightRewards": "Récompenses",
    "stealDrop": "Vol / butin",
    "previous": "Précédent",
    "next": "Suivant",
    "dontMiss": "À ne pas manquer",
    "items": "Objets",
    "secrets": "Secrets",
    "enemies": "Ennemis",
    "shops": "Boutiques et PNJ",
    "tips": "Astuces",
    "sourcesChecked": "Sources vérifiées : {list}",
    "guideOf": "Guide {game}",
    "checkedBadge": "Vérifié avec les sources",
    "allAreas": "Toutes les zones de ce guide",
    "areaTitle": "{area} – Guide {game} : objets, secrets et ennemis | Quest Compendium",
    "areaDesc": "Guide de {area} dans {game} : objets, secrets, éléments manquables et faiblesses des ennemis.",
    "gameTitle": "Guide et soluce de {game} | Quest Compendium",
    "gameDesc": "Guide zone par zone de {game} avec checklists d'objets, secrets, éléments manquables et faiblesses des ennemis.",
    "gameH1": "Guide {game}",
    "gameIntro": "Chaque zone dans l'ordre, avec checklists d'objets, secrets et éléments manquables. Vos cases cochées sont enregistrées dans ce navigateur.",
    "statAreas": "zones",
    "statThings": "choses à trouver",
    "statMissables": "manquables signalés",
    "statChecked": "pages vérifiées avec les sources",
    "statAreasOne": "zone",
    "statThingsOne": "élément à trouver",
    "statMissablesOne": "manquable signalé",
    "statCheckedOne": "page vérifiée avec les sources",
    "statAll": "Tout",
    "continue": "Reprendre là où vous en étiez",
    "indexTitle": "Guides de jeux et soluces | Quest Compendium",
    "indexDesc": "Guides de jeux avec checklists d'objets, secrets, éléments manquables et faiblesses des ennemis, zone par zone.",
    "indexH1": "Guides de jeux",
    "indexIntro": "Checklists zone par zone d'objets, de secrets et d'éléments manquables, plus les faiblesses des ennemis, pour {n} jeux.",
    "indexMore": "Plus de guides en anglais",
    "areasCount": "{n} zones",
    "areasCountOne": "1 zone",
    "none": "Les premiers guides arrivent bientôt.",
    "searchGames": "Rechercher des jeux…",
    "searchAreas": "Rechercher des zones et objets…",
    "sortAZ": "A–Z",
    "sortPopular": "Les plus populaires",
    "sortNew": "Les plus récents",
    "popular": "Populaires",
    "newGuides": "Nouveaux guides",
    "allGames": "Tous les jeux",
    "noMatches": "Aucun résultat trouvé.",
    "sortLabel": "Trier",
    "achTitle": "Guide des succès et roadmap de {game} : les {n} succès | Quest Compendium",
    "achDesc": "Les {n} succès de {game} : comment les débloquer, ceux à ne pas manquer et la roadmap du 100 %.",
    "achH1": "Guide des succès de {game}",
    "achIntro": "Comment débloquer chaque succès, ceux qui peuvent être manqués et le meilleur ordre pour tout obtenir. Cochez-les au fur et à mesure.",
    "achLink": "Guide des succès et roadmap",
    "achHere": "Succès dans cette zone",
    "searchAch": "Rechercher un succès…",
    "imagesNote": "Images du jeu © leurs propriétaires respectifs.",
    "achAll": "Tous les succès",
    "achMissable": "Manquable",
    "achRarity": "{n} % des joueurs",
    "achHidden": "Succès masqué : appuyez pour afficher",
    "achInArea": "Lieu : {area}",
    "rmTime": "Temps pour le 100 %",
    "rmDifficulty": "Difficulté",
    "rmPlaythroughs": "Parties nécessaires",
    "rmMissables": "Succès manquables",
    "rmSteps": "Ordre recommandé",
    "rmNoReturn": "Points de non-retour"
  },
  ja: {
    "navGuides": "攻略ガイド",
    "navGetApp": "アプリを入手",
    "language": "言語",
    "footerReport": "ガイドはAIを活用して作成されています。誤りを見つけた場合は{report}、または{discord}でお知らせください。ゲームの名称は各権利者に帰属し、当サイトはいかなるパブリッシャーとも提携していません。",
    "reportLink": "こちらから報告",
    "reportTitle": "誤りを報告する",
    "reportHint": "このページのどこに誤りがありますか？可能であれば、アイテム名、場所、または詳細をご記入ください。",
    "reportEntry": "どの項目が間違っていますか？（任意）",
    "reportEntryNone": "よくわからない / ページ全体",
    "reportCorrect": "正しい情報は何ですか？（任意）",
    "reportCorrectHint": "例：西の崖ではなく、倒木のそばの岩の下にある",
    "reportSend": "送信",
    "reportCancel": "キャンセル",
    "reportThanks": "ありがとうございます！内容を確認し、ガイドを修正します。",
    "reportError": "送信できませんでした。後でもう一度試すか、Discordでお知らせください。",
    "ctaTitle": "{game}で詰まっていませんか？",
    "ctaBody": "Quest Compendiumはプレイ中の画面を認識します。今いる場所について質問しながら、ゲームのすぐ隣でこのガイドを開いておけます。",
    "ctaButton": "プレイしながらリアルタイムでサポートを受ける",
    "gotIt": "了解",
    "weakTo": "弱点",
    "onThisPage": "このページの内容",
    "relatedQuests": "関連クエスト",
    "notListed": "このエリアの対象外: {list}",
    "itemHow": "入手方法",
    "itemLockout": "取り返しのつかない理由",
    "fights": "重要バトル",
    "fightEnemies": "出現エネミー",
    "fightThreats": "要注意攻撃",
    "fightWeak": "弱点と耐性",
    "fightTactics": "攻略のコツ",
    "fightRewards": "報酬",
    "stealDrop": "盗む / ドロップ",
    "previous": "前へ",
    "next": "次へ",
    "dontMiss": "見逃し注意",
    "items": "アイテム",
    "secrets": "隠し要素",
    "enemies": "敵",
    "shops": "ショップ＆NPC",
    "tips": "ヒント",
    "sourcesChecked": "確認済み情報源: {list}",
    "guideOf": "{game} 攻略ガイド",
    "checkedBadge": "情報源確認済み",
    "allAreas": "このガイドの全エリア",
    "areaTitle": "{area} – {game} 攻略: アイテム、隠し要素、敵 | Quest Compendium",
    "areaDesc": "{game}「{area}」の攻略情報: アイテム、隠し要素、取り返しのつかない要素、敵の弱点。",
    "gameTitle": "{game} 攻略・解説 | Quest Compendium",
    "gameDesc": "アイテムチェックリスト、隠し要素、取り返しのつかない要素、敵の弱点を網羅した{game}のエリア別攻略ガイド。",
    "gameH1": "{game} 攻略ガイド",
    "gameIntro": "全エリアを順を追って掲載。アイテム、隠し要素、取り返しのつかない要素のチェックリスト付き。チェック状態はこのブラウザに保存されます。",
    "statAreas": "エリア",
    "statThings": "収集要素",
    "statMissables": "見逃し要素マーク済み",
    "statChecked": "情報源確認済みページ",
    "statAreasOne": "エリア",
    "statThingsOne": "収集物",
    "statMissablesOne": "取り返しのつかない要素",
    "statCheckedOne": "情報ソース確認済みページ",
    "statAll": "すべて",
    "continue": "前回の続きから",
    "indexTitle": "ゲーム攻略ガイド一覧 | Quest Compendium",
    "indexDesc": "エリア別のアイテムチェックリスト、隠し要素、取り返しのつかない要素、敵の弱点を掲載したゲーム攻略ガイド。",
    "indexH1": "ゲーム攻略ガイド",
    "indexIntro": "{n}タイトルのアイテム、隠し要素、見逃し注意点、敵の弱点をエリア別チェックリストで掲載。",
    "indexMore": "英語版のガイドをもっと見る",
    "areasCount": "{n}エリア",
    "areasCountOne": "1エリア",
    "none": "最初のガイドを準備中です。",
    "searchGames": "ゲームを検索…",
    "searchAreas": "エリアやアイテムを検索…",
    "sortAZ": "五十音順",
    "sortPopular": "人気順",
    "sortNew": "新着順",
    "popular": "人気",
    "newGuides": "新着ガイド",
    "allGames": "すべてのゲーム",
    "noMatches": "一致する結果が見つかりませんでした。",
    "sortLabel": "並び替え",
    "achTitle": "{game} 実績ガイド＆ロードマップ：全{n}個の実績 | Quest Compendium",
    "achDesc": "全{n}個の{game}実績：解除方法、取り返しのつかない要素、100%達成へのロードマップ。",
    "achH1": "{game} 実績ガイド",
    "achIntro": "全実績の解除方法、取り逃しやすい実績、効率的な獲得順を解説。達成したらチェックしていこう。",
    "achLink": "実績ガイド＆ロードマップ",
    "achHere": "このエリアの実績",
    "searchAch": "実績を検索…",
    "imagesNote": "ゲーム画像の著作権は各権利者に帰属します。",
    "achAll": "すべての実績",
    "achMissable": "取り逃し注意",
    "achRarity": "プレイヤーの{n}%",
    "achHidden": "秘密の実績：タップして表示",
    "achInArea": "場所：{area}",
    "rmTime": "コンプまでの時間",
    "rmDifficulty": "難易度",
    "rmPlaythroughs": "周回数",
    "rmMissables": "取り逃しやすい実績",
    "rmSteps": "おすすめの手順",
    "rmNoReturn": "後戻りできないポイント"
  },
  ko: {
    "navGuides": "공략",
    "navGetApp": "앱 다운로드",
    "language": "언어",
    "footerReport": "가이드는 AI의 도움을 받아 작성되었습니다. 잘못된 내용이 있나요? {report}에 제보하시거나 {discord}를 통해 알려주세요. 게임 이름의 저작권은 해당 소유자에게 있으며, 이 사이트는 어떤 게임 유통사와도 관련이 없습니다.",
    "reportLink": "여기서 제보하기",
    "reportTitle": "오류 제보",
    "reportHint": "이 페이지에서 어떤 부분이 잘못되었나요? 가능한 경우 아이템, 장소 또는 구체적인 내용을 알려주세요.",
    "reportEntry": "어떤 항목이 잘못되었나요? (선택 사항)",
    "reportEntryNone": "잘 모르겠음 또는 페이지 전체",
    "reportCorrect": "올바른 내용은 무엇인가요? (선택 사항)",
    "reportCorrectHint": "예: 서쪽 절벽이 아니라 쓰러진 통나무 옆 바위 아래에 있어요",
    "reportSend": "보내기",
    "reportCancel": "취소",
    "reportThanks": "감사합니다! 확인 후 가이드를 수정하겠습니다.",
    "reportError": "전송에 실패했습니다. 나중에 다시 시도하거나 Discord를 통해 알려주세요.",
    "ctaTitle": "{game} 진행 중 막히셨나요?",
    "ctaBody": "Quest Compendium은 플레이 중인 화면을 인식합니다. 지금 있는 위치에 대해 바로 물어보고, 게임 화면 옆에 이 가이드를 띄워두고 플레이하세요.",
    "ctaButton": "플레이하며 실시간 도움 받기",
    "gotIt": "확인",
    "weakTo": "약점 속성",
    "onThisPage": "이 페이지의 내용",
    "relatedQuests": "관련 퀘스트",
    "notListed": "이 지역에 미포함: {list}.",
    "itemHow": "획득 방법",
    "itemLockout": "놓치기 쉬운 이유",
    "fights": "주요 전투",
    "fightEnemies": "적",
    "fightThreats": "위협 요소",
    "fightWeak": "약점 및 내성",
    "fightTactics": "전술",
    "fightRewards": "보상",
    "stealDrop": "훔치기 / 드롭",
    "previous": "이전",
    "next": "다음",
    "dontMiss": "놓치기 쉬운 요소",
    "items": "아이템",
    "secrets": "비밀 요소",
    "enemies": "적 정보",
    "shops": "상점 및 NPC",
    "tips": "팁",
    "sourcesChecked": "교차 검증된 출처: {list}",
    "guideOf": "{game} 공략",
    "checkedBadge": "출처 검증 완료",
    "allAreas": "이 공략의 모든 구역",
    "areaTitle": "{area} – {game} 공략: 아이템, 비밀 요소, 적 정보 | Quest Compendium",
    "areaDesc": "{game} {area} 가이드: 아이템, 비밀 요소, 놓치기 쉬운 것들 및 적 약점.",
    "gameTitle": "{game} 공략 및 완벽 가이드 | Quest Compendium",
    "gameDesc": "구역별 {game} 공략: 아이템 체크리스트, 비밀 요소, 놓치기 쉬운 것들 및 적 약점 수록.",
    "gameH1": "{game} 공략",
    "gameIntro": "모든 구역을 순서대로 정리했으며 아이템, 비밀 요소, 놓치기 쉬운 것들의 체크리스트를 제공합니다. 체크 표시는 이 브라우저에 저장됩니다.",
    "statAreas": "개 구역",
    "statThings": "개 수집 요소",
    "statMissables": "개 놓치기 쉬운 요소",
    "statChecked": "개 페이지 교차 검증 완료",
    "statAreasOne": "지역",
    "statThingsOne": "수집 요소",
    "statMissablesOne": "놓치기 쉬운 항목 표시됨",
    "statCheckedOne": "출처 대조 확인 완료",
    "statAll": "전체",
    "continue": "이어서 보기",
    "indexTitle": "게임 공략 및 완벽 가이드 | Quest Compendium",
    "indexDesc": "구역별 아이템 체크리스트, 비밀 요소, 놓치기 쉬운 것들 및 적 약점이 정리된 게임 공략입니다.",
    "indexH1": "게임 공략",
    "indexIntro": "{n}개 게임에 대한 구역별 아이템, 비밀 요소, 놓치기 쉬운 것들 체크리스트와 적 약점을 제공합니다.",
    "indexMore": "더 많은 영어 공략",
    "areasCount": "{n}개 구역",
    "areasCountOne": "1개 구역",
    "none": "첫 번째 공략을 곧 공개할 예정입니다.",
    "searchGames": "게임 검색…",
    "searchAreas": "지역 및 아이템 검색…",
    "sortAZ": "가나다순",
    "sortPopular": "인기순",
    "sortNew": "최신순",
    "popular": "인기",
    "newGuides": "새 가이드",
    "allGames": "모든 게임",
    "noMatches": "검색 결과가 없습니다.",
    "sortLabel": "정렬",
    "achTitle": "{game} 도전과제 가이드 & 로드맵: 총 {n}개 도전과제 | Quest Compendium",
    "achDesc": "{game}의 도전과제 총 {n}개 완벽 정리: 달성 방법, 놓치기 쉬운 과제, 100% 달성 로드맵.",
    "achH1": "{game} 도전과제 가이드",
    "achIntro": "모든 도전과제 달성 방법, 놓치기 쉬운 과제, 최적의 진행 순서를 확인하세요. 완료한 항목은 체크하며 진행할 수 있습니다.",
    "achLink": "도전과제 가이드 및 로드맵",
    "achHere": "이 지역의 도전과제",
    "searchAch": "도전과제 검색…",
    "imagesNote": "게임 이미지의 저작권은 각 권리자에게 있습니다.",
    "achAll": "전체 도전과제",
    "achMissable": "놓치기 쉬움",
    "achRarity": "달성한 플레이어: {n}%",
    "achHidden": "숨겨진 도전과제: 탭하여 확인",
    "achInArea": "위치: {area}",
    "rmTime": "100% 달성 소요 시간",
    "rmDifficulty": "난이도",
    "rmPlaythroughs": "필요 회차",
    "rmMissables": "놓치기 쉬운 도전과제",
    "rmSteps": "추천 진행 순서",
    "rmNoReturn": "되돌아갈 수 없는 지점"
  },
  pt: {
    "navGuides": "Guias",
    "navGetApp": "Baixar o app",
    "language": "Idioma",
    "footerReport": "Os guias são criados com a ajuda de IA. Viu algum erro? {report} ou avise a gente no {discord}. Os nomes dos jogos pertencem aos seus donos; este site não é afiliado a nenhuma distribuidora.",
    "reportLink": "Reporte aqui",
    "reportTitle": "Reportar um erro",
    "reportHint": "O que está errado nesta página? Cite o item, local ou detalhe, se puder.",
    "reportEntry": "Qual entrada está incorreta? (opcional)",
    "reportEntryNone": "Não tenho certeza ou a página inteira",
    "reportCorrect": "Qual é o correto? (opcional)",
    "reportCorrectHint": "ex.: fica embaixo da pedra perto do tronco caído, não nos penhascos a oeste",
    "reportSend": "Enviar",
    "reportCancel": "Cancelar",
    "reportThanks": "Valeu! Vamos verificar e corrigir o guia.",
    "reportError": "Não foi possível enviar. Tente de novo mais tarde ou avise a gente no Discord.",
    "ctaTitle": "Empacou em alguma parte de {game}?",
    "ctaBody": "O Quest Compendium reconhece sua tela enquanto você joga: pergunte sobre exatamente onde você está e mantenha este guia aberto lado a lado com o jogo.",
    "ctaButton": "Receba ajuda ao vivo enquanto joga",
    "gotIt": "Entendi",
    "weakTo": "Fraqueza:",
    "onThisPage": "Nesta página",
    "relatedQuests": "Missões relacionadas",
    "notListed": "Não listado para esta área: {list}.",
    "itemHow": "Como obter",
    "itemLockout": "Pode ser perdido porque",
    "fights": "Batalhas principais",
    "fightEnemies": "Inimigos",
    "fightThreats": "Ameaças",
    "fightWeak": "Fraquezas e resistências",
    "fightTactics": "Táticas",
    "fightRewards": "Recompensas",
    "stealDrop": "Roubo / drop",
    "previous": "Anterior",
    "next": "Próximo",
    "dontMiss": "Imperdível",
    "items": "Itens",
    "secrets": "Segredos",
    "enemies": "Inimigos",
    "shops": "Lojas e NPCs",
    "tips": "Dicas",
    "sourcesChecked": "Fontes verificadas: {list}",
    "guideOf": "Guia de {game}",
    "checkedBadge": "Conferido com fontes",
    "allAreas": "Todas as áreas deste guia",
    "areaTitle": "{area} – Guia de {game}: Itens, Segredos e Inimigos | Quest Compendium",
    "areaDesc": "Guia de {area} em {game}: itens, segredos, itens perdíveis e fraquezas de inimigos.",
    "gameTitle": "Guia e Detonado de {game} | Quest Compendium",
    "gameDesc": "Guia área por área de {game} com checklists de itens, segredos, itens perdíveis e fraquezas de inimigos.",
    "gameH1": "Guia de {game}",
    "gameIntro": "Todas as áreas em ordem, com checklists de itens, segredos e itens perdíveis. O progresso fica salvo neste navegador.",
    "statAreas": "áreas",
    "statThings": "coisas para achar",
    "statMissables": "itens perdíveis marcados",
    "statChecked": "páginas conferidas com fontes",
    "statAreasOne": "área",
    "statThingsOne": "item para achar",
    "statMissablesOne": "perdível marcado",
    "statCheckedOne": "página verificada com as fontes",
    "statAll": "Tudo",
    "continue": "Continuar de onde você parou",
    "indexTitle": "Guias de Jogos e Detonados | Quest Compendium",
    "indexDesc": "Guias de jogos com checklists de itens, segredos, itens perdíveis e fraquezas de inimigos, área por área.",
    "indexH1": "Guias de jogos",
    "indexIntro": "Checklists área por área de itens, segredos e itens perdíveis, além de fraquezas de inimigos, para {n} jogos.",
    "indexMore": "Mais guias em inglês",
    "areasCount": "{n} áreas",
    "areasCountOne": "1 área",
    "none": "Os primeiros guias chegam em breve.",
    "searchGames": "Buscar jogos…",
    "searchAreas": "Buscar áreas e itens…",
    "sortAZ": "A–Z",
    "sortPopular": "Mais populares",
    "sortNew": "Mais recentes",
    "popular": "Populares",
    "newGuides": "Novos guias",
    "allGames": "Todos os jogos",
    "noMatches": "Nenhum resultado encontrado.",
    "sortLabel": "Ordenar",
    "achTitle": "Guia de Conquistas e Roadmap de {game}: Todas as {n} Conquistas | Quest Compendium",
    "achDesc": "Todas as {n} conquistas de {game}: como desbloquear cada uma, quais são perdíveis e o roadmap rumo aos 100%.",
    "achH1": "Guia de conquistas de {game}",
    "achIntro": "Como desbloquear cada conquista, quais você pode perder e a melhor ordem para pegar todas. Marque-as conforme avança.",
    "achLink": "Guia de conquistas e roadmap",
    "achHere": "Conquistas aqui",
    "searchAch": "Buscar conquistas…",
    "imagesNote": "Imagens do jogo © seus respectivos proprietários.",
    "achAll": "Todas as conquistas",
    "achMissable": "Perdível",
    "achRarity": "{n}% dos jogadores",
    "achHidden": "Conquista secreta: toque para revelar",
    "achInArea": "Onde: {area}",
    "rmTime": "Tempo até 100%",
    "rmDifficulty": "Dificuldade",
    "rmPlaythroughs": "Campanhas",
    "rmMissables": "Conquistas perdíveis",
    "rmSteps": "Ordem recomendada",
    "rmNoReturn": "Pontos sem retorno"
  },
  ru: {
    "navGuides": "Гайды",
    "navGetApp": "Скачать приложение",
    "language": "Язык",
    "footerReport": "Гайды написаны с помощью ИИ. Заметили ошибку? {report} или напишите нам в {discord}. Названия игр принадлежат их владельцам; сайт не связан с издателями.",
    "reportLink": "Сообщите о ней здесь",
    "reportTitle": "Сообщить об ошибке",
    "reportHint": "Что не так на этой странице? Если помните, укажите предмет, место или деталь.",
    "reportEntry": "Какая запись неверна? (необязательно)",
    "reportEntryNone": "Не знаю точно, или вся страница",
    "reportCorrect": "Как правильно? (необязательно)",
    "reportCorrectHint": "например: под камнем у поваленного бревна, а не на западных скалах",
    "reportSend": "Отправить",
    "reportCancel": "Отмена",
    "reportThanks": "Спасибо! Мы всё проверим и исправим гайд.",
    "reportError": "Не удалось отправить. Попробуйте позже или напишите нам в Discord.",
    "ctaTitle": "Застряли в {game}?",
    "ctaBody": "Quest Compendium видит ваш экран во время игры: задавайте вопросы о текущей локации и держите этот гайд под рукой прямо поверх игры.",
    "ctaButton": "Помощь в игре в реальном времени",
    "gotIt": "Понятно",
    "weakTo": "Уязвимость к",
    "onThisPage": "На этой странице",
    "relatedQuests": "Связанные квесты",
    "notListed": "Не указано для этой зоны: {list}.",
    "itemHow": "Как получить",
    "itemLockout": "Можно пропустить, так как",
    "fights": "Ключевые бои",
    "fightEnemies": "Враги",
    "fightThreats": "Угрозы",
    "fightWeak": "Уязвимости и сопротивления",
    "fightTactics": "Тактика",
    "fightRewards": "Награды",
    "stealDrop": "Кража / дроп",
    "previous": "Назад",
    "next": "Вперед",
    "dontMiss": "Не пропустите",
    "items": "Предметы",
    "secrets": "Секреты",
    "enemies": "Враги",
    "shops": "Торговцы и NPC",
    "tips": "Советы",
    "sourcesChecked": "Проверенные источники: {list}",
    "guideOf": "Гайд по {game}",
    "checkedBadge": "Сверено с источниками",
    "allAreas": "Все локации гайда",
    "areaTitle": "{area} — Гайд по {game}: предметы, секреты и враги | Quest Compendium",
    "areaDesc": "Гайд по локации {area} в {game}: предметы, секреты, пропускаемый контент и уязвимости врагов.",
    "gameTitle": "Гайд и прохождение {game} | Quest Compendium",
    "gameDesc": "Пошаговый гайд по {game} с чек-листами предметов, секретами, пропускаемым лутом и уязвимостями врагов.",
    "gameH1": "Гайд по {game}",
    "gameIntro": "Все локации по порядку, с чек-листами предметов, секретов и пропускаемых вещей. Отметки сохраняются в браузере.",
    "statAreas": "локаций",
    "statThings": "находок",
    "statMissables": "пропускаемых предметов",
    "statChecked": "страниц проверено по источникам",
    "statAreasOne": "локация",
    "statThingsOne": "секрет",
    "statMissablesOne": "пропускаемый предмет",
    "statCheckedOne": "страница сверена с источниками",
    "statAll": "Все",
    "continue": "Продолжить с места остановки",
    "indexTitle": "Гайды и прохождения игр | Quest Compendium",
    "indexDesc": "Гайды по локациям с чек-листами предметов, секретами, пропускаемым лутом и уязвимостями врагов.",
    "indexH1": "Игровые гайды",
    "indexIntro": "Чек-листы локаций с предметами, секретами и пропускаемым контентом, а также уязвимости врагов для {n} игр.",
    "indexMore": "Больше гайдов на английском",
    "areasCount": "Локаций: {n}",
    "areasCountOne": "1 локация",
    "none": "Первые гайды уже готовятся к выходу.",
    "searchGames": "Поиск игр…",
    "searchAreas": "Поиск локаций и предметов…",
    "sortAZ": "А–Я",
    "sortPopular": "Популярные",
    "sortNew": "Свежие",
    "popular": "Популярное",
    "newGuides": "Новые гайды",
    "allGames": "Все игры",
    "noMatches": "Ничего не нашлось.",
    "sortLabel": "Сортировка",
    "achTitle": "Гайд по достижениям {game}: все {n} ачивок | Quest Compendium",
    "achDesc": "Все {n} достижений в {game}: как открыть каждое, какие можно пропустить и маршрут до 100%.",
    "achH1": "Гайд по достижениям {game}",
    "achIntro": "Как открыть все достижения, какие из них можно пропустить и в каком порядке их выбивать. Отмечайте прогресс на ходу.",
    "achLink": "Гайд по достижениям и маршрут",
    "achHere": "Достижения здесь",
    "searchAch": "Поиск достижений…",
    "imagesNote": "Изображения из игр © принадлежат их владельцам.",
    "achAll": "Все достижения",
    "achMissable": "Пропускаемые",
    "achRarity": "{n}% игроков",
    "achHidden": "Скрытое достижение: нажмите, чтобы открыть",
    "achInArea": "Где: {area}",
    "rmTime": "Время до 100%",
    "rmDifficulty": "Сложность",
    "rmPlaythroughs": "Прохождений",
    "rmMissables": "Пропускаемые ачивки",
    "rmSteps": "Рекомендуемый порядок",
    "rmNoReturn": "Точки невозврата"
  },
  zh: {
    "navGuides": "攻略",
    "navGetApp": "获取应用",
    "language": "语言",
    "footerReport": "本攻略由 AI 辅助撰写。发现错误？请{report}，或在 {discord} 上告诉我们。游戏名称归其版权方所有；本站与任何游戏发行商均无从属关系。",
    "reportLink": "在此报错",
    "reportTitle": "报错反馈",
    "reportHint": "本页有什么错误？可以的话，请指出具体的物品、地点或细节。",
    "reportEntry": "哪个条目有误？（可选）",
    "reportEntryNone": "不确定，或整页都有问题",
    "reportCorrect": "正确内容是什么？（可选）",
    "reportCorrectHint": "例如：是在倒下的原木旁边的石头下，而不是在西边的悬崖上",
    "reportSend": "发送",
    "reportCancel": "取消",
    "reportThanks": "感谢反馈！我们会核对并尽快修正攻略。",
    "reportError": "发送失败。请稍后再试，或在 Discord 上告诉我们。",
    "ctaTitle": "在《{game}》中卡关了？",
    "ctaBody": "Quest Compendium 可以在你游玩时读取屏幕：针对你当前的位置精准提问，攻略常驻游戏旁随时查看。",
    "ctaButton": "边玩边获取实时帮助",
    "gotIt": "知道了",
    "weakTo": "弱点属性",
    "onThisPage": "本页导览",
    "relatedQuests": "相关任务",
    "notListed": "未列入该区域：{list}。",
    "itemHow": "获取方法",
    "itemLockout": "错过原因",
    "fights": "关键战斗",
    "fightEnemies": "敌人",
    "fightThreats": "威胁",
    "fightWeak": "弱点与抗性",
    "fightTactics": "战术",
    "fightRewards": "奖励",
    "stealDrop": "偷窃 / 掉落",
    "previous": "上一页",
    "next": "下一页",
    "dontMiss": "切勿错过",
    "items": "物品",
    "secrets": "秘密",
    "enemies": "敌人",
    "shops": "商店与 NPC",
    "tips": "提示",
    "sourcesChecked": "参考资料核对：{list}",
    "guideOf": "《{game}》攻略",
    "checkedBadge": "已核对资料来源",
    "allAreas": "本攻略包含的所有区域",
    "areaTitle": "{area} – 《{game}》攻略：物品、秘密与敌人 | Quest Compendium",
    "areaDesc": "《{game}》{area}区域攻略：物品、秘密、易错过内容和敌人弱点。",
    "gameTitle": "《{game}》完整攻略与流程指引 | Quest Compendium",
    "gameDesc": "分区域《{game}》全攻略，包含物品清单、秘密、易错过要素和敌人弱点。",
    "gameH1": "《{game}》攻略",
    "gameIntro": "按顺序整理的每个区域攻略，附带物品、秘密和易错过内容的核对清单。你的勾选进度会自动保存在当前浏览器中。",
    "statAreas": "个区域",
    "statThings": "处可探索内容",
    "statMissables": "处易错过标记",
    "statChecked": "页已核对资料",
    "statAreasOne": "个区域",
    "statThingsOne": "处可探索内容",
    "statMissablesOne": "处易遗漏内容已标记",
    "statCheckedOne": "页已核对数据源",
    "statAll": "全部",
    "continue": "继续上次的进度",
    "indexTitle": "游戏攻略与流程指引 | Quest Compendium",
    "indexDesc": "分区域游戏攻略，包含物品清单、秘密、易错过要素及敌人弱点。",
    "indexH1": "游戏攻略",
    "indexIntro": "涵盖 {n} 款游戏的分区域核对清单，包含物品、秘密、易错过要素以及敌人弱点。",
    "indexMore": "更多英文攻略",
    "areasCount": "{n} 个区域",
    "areasCountOne": "1 个区域",
    "none": "首批攻略正在路上，敬请期待。",
    "searchGames": "搜索游戏…",
    "searchAreas": "搜索区域和物品…",
    "sortAZ": "A–Z",
    "sortPopular": "最受欢迎",
    "sortNew": "最新",
    "popular": "热门",
    "newGuides": "最新攻略",
    "allGames": "全部游戏",
    "noMatches": "未找到匹配结果。",
    "sortLabel": "排序",
    "achTitle": "{game} 成就指南与全成就路线：全部 {n} 个成就 | Quest Compendium",
    "achDesc": "《{game}》全部 {n} 个成就解锁指南：易遗漏成就提醒与 100% 全成就路线规划。",
    "achH1": "{game} 成就指南",
    "achIntro": "详解每个成就的解锁方式、易遗漏成就以及最佳获取顺序。边玩边勾选，全成就更轻松。",
    "achLink": "成就指南与全成就路线",
    "achHere": "本区域成就",
    "searchAch": "搜索成就…",
    "imagesNote": "游戏图片版权归其各自所有者所有。",
    "achAll": "全部成就",
    "achMissable": "易遗漏",
    "achRarity": "{n}% 的玩家拥有",
    "achHidden": "隐藏成就：点击查看",
    "achInArea": "地点：{area}",
    "rmTime": "全成就耗时",
    "rmDifficulty": "全成就难度",
    "rmPlaythroughs": "通关周目",
    "rmMissables": "易遗漏成就",
    "rmSteps": "推荐流程",
    "rmNoReturn": "不可返回节点"
  },
};
