/**
 * The website guide pages' own words (headings, buttons, labels), in English. Other languages are AI translations
 * in guide-ui.generated.ts, made with `npx tsx scripts/i18n/translate.ts --target guide-ui`. Guide content itself is
 * translated per game with scripts/guides/translate-guide.ts.
 */
export const GUIDE_UI_EN: Record<string, string> = {
  navGuides: 'Guides',
  navGetApp: 'Get the app',
  language: 'Language',
  footerReport: 'Guides are written with AI help. Spot a mistake? {report}, or tell us on {discord}. Game names belong to their owners; this site isn\'t affiliated with any publisher.',
  reportLink: 'Report it here',
  reportTitle: 'Report a mistake',
  reportHint: 'What\'s wrong on this page? Name the item, place or detail if you can.',
  reportEntry: 'Which entry is wrong? (optional)',
  reportEntryNone: 'Not sure, or the whole page',
  reportCorrect: "What's correct? (optional)",
  reportCorrectHint: "e.g. it's under the rock by the fallen log, not on the western cliffs",
  reportSend: 'Send',
  reportCancel: 'Cancel',
  reportThanks: 'Thanks! We\'ll check it and fix the guide.',
  reportError: 'That didn\'t send. Try again later, or tell us on Discord.',
  ctaTitle: 'Stuck somewhere in {game}?',
  ctaBody: 'Quest Compendium sees your screen while you play: ask about exactly where you are, and keep this guide open right beside your game.',
  ctaButton: 'Get live help while you play',
  gotIt: 'Got it',
  weakTo: 'Weak to',
  onThisPage: 'On this page',
  relatedQuests: 'Related quests',
  notListed: 'Not listed for this area: {list}.',
  itemHow: 'How',
  itemLockout: 'Missable because',
  fights: 'Key fights',
  fightEnemies: 'Enemies',
  fightThreats: 'Threats',
  fightWeak: 'Weaknesses and resistances',
  fightTactics: 'Tactics',
  fightRewards: 'Rewards',
  stealDrop: 'Steal / drop',
  previous: 'Previous',
  next: 'Next',
  dontMiss: "Don't miss",
  items: 'Items',
  secrets: 'Secrets',
  enemies: 'Enemies',
  shops: 'Shops and people',
  tips: 'Tips',
  sourcesChecked: 'Sources checked: {list}',
  guideOf: '{game} guide',
  checkedBadge: 'Checked against sources',
  allAreas: 'All areas in this guide',
  areaTitle: '{area} – {game} Guide: Items, Secrets & Enemies | Quest Compendium',
  areaDesc: '{game} {area} guide: items, secrets, missables and enemy weaknesses.',
  gameTitle: '{game} Guide and Walkthrough | Quest Compendium',
  gameDesc: 'Area-by-area {game} guide with item checklists, secrets, missables and enemy weaknesses.',
  gameH1: '{game} guide',
  gameIntro: 'Every area in order, with checklists of items, secrets and missables. Your ticks are saved in this browser.',
  statAreas: 'areas',
  statThings: 'things to find',
  statMissables: 'missables flagged',
  statChecked: 'pages checked against sources',
  // The same stats when the number is 1 ("1 area", not "1 areas").
  statAreasOne: 'area',
  statThingsOne: 'thing to find',
  statMissablesOne: 'missable flagged',
  statCheckedOne: 'page checked against sources',
  statAll: 'All',
  continue: 'Continue where you left off',
  indexTitle: 'Game Guides and Walkthroughs | Quest Compendium',
  indexDesc: 'Game guides with item checklists, secrets, missables and enemy weaknesses, area by area.',
  indexH1: 'Game guides',
  indexIntro: 'Area-by-area checklists of items, secrets and missables, plus enemy weaknesses, for {n} games.',
  indexMore: 'More guides in English',
  areasCount: '{n} areas',
  areasCountOne: '1 area',
  none: 'The first guides are on their way.',
  searchGames: 'Search games…',
  searchAreas: 'Search areas and items…',
  sortAZ: 'A–Z',
  sortPopular: 'Most popular',
  sortNew: 'Newest',
  popular: 'Popular',
  newGuides: 'New guides',
  allGames: 'All games',
  noMatches: 'Nothing matches that search.',
  sortLabel: 'Sort',
  achTitle: '{game} Achievement Guide & Roadmap: All {n} Achievements | Quest Compendium',
  achDesc: 'All {n} {game} achievements: how to unlock each one, which are missable, and a roadmap to 100%.',
  achH1: '{game} achievement guide',
  achIntro: 'How to unlock every achievement, which ones you can miss, and the best order to get them all. Tick them off as you go.',
  achLink: 'Achievement guide and roadmap',
  achHere: 'Achievements here',
  searchAch: 'Search achievements…',
  imagesNote: 'Game images © their respective owners.',
  achAll: 'All achievements',
  achMissable: 'Missable',
  achRarity: '{n}% of players',
  achHidden: 'Hidden achievement: tap to reveal',
  achInArea: 'Where: {area}',
  rmTime: 'Time to 100%',
  rmDifficulty: 'Difficulty',
  rmPlaythroughs: 'Playthroughs',
  rmMissables: 'Missable achievements',
  rmSteps: 'Recommended order',
  rmNoReturn: 'Points of no return',
};
export const SOURCE_STRINGS = GUIDE_UI_EN;
export const HAND_WRITTEN = {};
