/**
 * AI translations of the interface, written by scripts/i18n/translate.ts in the Quest Compendium repo (run it again
 * after adding English strings or a language). Used after the hand-written dictionaries; anything missing falls back
 * to English.
 */
export const GENERATED: Record<string, Record<string, string>> = {
  de: {
    "navGuides": "Guides",
    "navGetApp": "App holen",
    "language": "Sprache",
    "footer": "Guides werden mit KI-Hilfe erstellt. Fehler gefunden? Sag es uns auf {discord}. Spielnamen gehören ihren Eigentümern; diese Seite ist mit keinem Publisher verbunden.",
    "ctaTitle": "Kommst du in {game} nicht weiter?",
    "ctaBody": "Quest Compendium sieht deinen Bildschirm beim Spielen: Frag genau nach deiner Stelle und hab diesen Guide direkt neben dem Spiel offen.",
    "ctaButton": "Live-Hilfe beim Spielen holen",
    "gotIt": "Verstanden",
    "weakTo": "Schwach gegen",
    "stealDrop": "Stehlen / Beute",
    "previous": "Zurück",
    "next": "Weiter",
    "dontMiss": "Nicht verpassen",
    "items": "Gegenstände",
    "secrets": "Geheimnisse",
    "enemies": "Gegner",
    "shops": "Händler & NPCs",
    "tips": "Tipps",
    "sourcesChecked": "Geprüfte Quellen: {list}",
    "guideOf": "{game} Guide",
    "checkedBadge": "Gegen Quellen geprüft",
    "allAreas": "Alle Gebiete in diesem Guide",
    "areaTitle": "{area} – {game} Guide: Items, Geheimnisse & Gegner | Quest Compendium",
    "areaDesc": "{game} {area} Guide: Items, Geheimnisse, Verpassbares und Gegnerschwächen.",
    "gameTitle": "{game} Guide & Komplettlösung | Quest Compendium",
    "gameDesc": "Gebiets-Guide für {game} mit Item-Checklisten, Geheimnissen, Verpassbarem und Gegnerschwächen.",
    "gameH1": "{game} Guide",
    "gameIntro": "Jedes Gebiet nach der Reihe, mit Checklisten für Items, Geheimnisse und Verpassbares. Deine Haken werden in diesem Browser gespeichert.",
    "statAreas": "Gebiete",
    "statThings": "Dinge zu finden",
    "statMissables": "Verpassbare markiert",
    "statChecked": "Seiten gegen Quellen geprüft",
    "statAll": "Alle",
    "continue": "Da weitermachen, wo du aufgehört hast",
    "indexTitle": "Game Guides & Komplettlösungen | Quest Compendium",
    "indexDesc": "Game-Guides mit Item-Checklisten, Geheimnissen, Verpassbarem und Gegnerschwächen – Gebiet für Gebiet.",
    "indexH1": "Game-Guides",
    "indexIntro": "Gebiet-für-Gebiet-Checklisten für Items, Geheimnisse, Verpassbares und Gegnerschwächen für {n} Spiele.",
    "indexMore": "Weitere Guides auf Englisch",
    "areasCount": "{n} Gebiete",
    "areasCountOne": "1 Gebiet",
    "none": "Die ersten Guides sind schon unterwegs."
  },
  es: {
    "navGuides": "Guías",
    "navGetApp": "Obtén la app",
    "language": "Idioma",
    "footer": "Las guías se escriben con ayuda de IA. ¿Ves un error? Cuéntanos en {discord}. Los nombres de juegos pertenecen a sus respectivos dueños; este sitio no está afiliado con ninguna distribuidora.",
    "ctaTitle": "¿Te trabaste en {game}?",
    "ctaBody": "Quest Compendium ve tu pantalla mientras juegas: pregunta exactamente sobre dónde estás y mantén esta guía abierta junto a tu juego.",
    "ctaButton": "Recibe ayuda en vivo mientras juegas",
    "gotIt": "Entendido",
    "weakTo": "Débil contra",
    "stealDrop": "Robo / botín",
    "previous": "Anterior",
    "next": "Siguiente",
    "dontMiss": "Imperdibles",
    "items": "Objetos",
    "secrets": "Secretos",
    "enemies": "Enemigos",
    "shops": "Tiendas y personajes",
    "tips": "Consejos",
    "sourcesChecked": "Fuentes verificadas: {list}",
    "guideOf": "Guía de {game}",
    "checkedBadge": "Verificado con fuentes",
    "allAreas": "Todas las zonas de esta guía",
    "areaTitle": "{area} – Guía de {game}: Objetos, secretos y enemigos | Quest Compendium",
    "areaDesc": "Guía de {area} en {game}: objetos, secretos, coleccionables que se pueden perder y debilidades de enemigos.",
    "gameTitle": "Guía y walkthrough de {game} | Quest Compendium",
    "gameDesc": "Guía zona por zona de {game} con listas de objetos, secretos, cosas que puedes perderte y debilidades enemigas.",
    "gameH1": "Guía de {game}",
    "gameIntro": "Cada zona en orden, con listas de objetos, secretos y cosas que puedes perderte. Tu progreso se guarda en este navegador.",
    "statAreas": "zonas",
    "statThings": "cosas por encontrar",
    "statMissables": "imperdibles marcados",
    "statChecked": "páginas verificadas con fuentes",
    "statAll": "Todo",
    "continue": "Continúa donde lo dejaste",
    "indexTitle": "Guías de juegos y walkthroughs | Quest Compendium",
    "indexDesc": "Guías de juegos con listas de objetos, secretos, cosas que puedes perderte y debilidades de enemigos, zona por zona.",
    "indexH1": "Guías de juegos",
    "indexIntro": "Listas zona por zona de objetos, secretos y cosas que puedes perderte, además de debilidades de enemigos, para {n} juegos.",
    "indexMore": "Más guías en inglés",
    "areasCount": "{n} zonas",
    "areasCountOne": "1 zona",
    "none": "Las primeras guías ya vienen en camino."
  },
  fr: {
    "navGuides": "Guides",
    "navGetApp": "Télécharger l'app",
    "language": "Langue",
    "footer": "Guides rédigés avec l'aide de l'IA. Une erreur ? Dites-le-nous sur {discord}. Les noms de jeux appartiennent à leurs propriétaires respectifs ; ce site n'est affilié à aucun éditeur.",
    "ctaTitle": "Bloqué dans {game} ?",
    "ctaBody": "Quest Compendium analyse votre écran pendant que vous jouez : posez vos questions selon l'endroit où vous êtes et gardez ce guide ouvert juste à côté de votre jeu.",
    "ctaButton": "Obtenir de l'aide en direct en jeu",
    "gotIt": "Compris",
    "weakTo": "Faiblesses",
    "stealDrop": "Vol / butin",
    "previous": "Précédent",
    "next": "Suivant",
    "dontMiss": "À ne pas manquer",
    "items": "Objets",
    "secrets": "Secrets",
    "enemies": "Ennemis",
    "shops": "Boutiques et PNJ",
    "tips": "Astuces",
    "sourcesChecked": "Sources vérifiées : {list}",
    "guideOf": "Guide {game}",
    "checkedBadge": "Vérifié avec les sources",
    "allAreas": "Toutes les zones de ce guide",
    "areaTitle": "{area} – Guide {game} : objets, secrets et ennemis | Quest Compendium",
    "areaDesc": "Guide de {area} dans {game} : objets, secrets, éléments manquables et faiblesses des ennemis.",
    "gameTitle": "Guide et soluce de {game} | Quest Compendium",
    "gameDesc": "Guide zone par zone de {game} avec checklists d'objets, secrets, éléments manquables et faiblesses des ennemis.",
    "gameH1": "Guide {game}",
    "gameIntro": "Chaque zone dans l'ordre, avec checklists d'objets, secrets et éléments manquables. Vos cases cochées sont enregistrées dans ce navigateur.",
    "statAreas": "zones",
    "statThings": "choses à trouver",
    "statMissables": "manquables signalés",
    "statChecked": "pages vérifiées avec les sources",
    "statAll": "Tout",
    "continue": "Reprendre là où vous en étiez",
    "indexTitle": "Guides de jeux et soluces | Quest Compendium",
    "indexDesc": "Guides de jeux avec checklists d'objets, secrets, éléments manquables et faiblesses des ennemis, zone par zone.",
    "indexH1": "Guides de jeux",
    "indexIntro": "Checklists zone par zone d'objets, de secrets et d'éléments manquables, plus les faiblesses des ennemis, pour {n} jeux.",
    "indexMore": "Plus de guides en anglais",
    "areasCount": "{n} zones",
    "areasCountOne": "1 zone",
    "none": "Les premiers guides arrivent bientôt."
  },
  ja: {
    "navGuides": "攻略ガイド",
    "navGetApp": "アプリを入手",
    "language": "言語",
    "footer": "ガイドはAIを活用して作成されています。誤りを見つけた場合は{discord}でお知らせください。ゲームの名称は各権利者に帰属します。当サイトはどのパブリッシャーとも提携していません。",
    "ctaTitle": "{game}で詰まっていませんか？",
    "ctaBody": "Quest Compendiumはプレイ中の画面を認識します。今いる場所について質問しながら、ゲームのすぐ隣でこのガイドを開いておけます。",
    "ctaButton": "プレイしながらリアルタイムでサポートを受ける",
    "gotIt": "了解",
    "weakTo": "弱点",
    "stealDrop": "盗む / ドロップ",
    "previous": "前へ",
    "next": "次へ",
    "dontMiss": "見逃し注意",
    "items": "アイテム",
    "secrets": "隠し要素",
    "enemies": "敵",
    "shops": "ショップ＆NPC",
    "tips": "ヒント",
    "sourcesChecked": "確認済み情報源: {list}",
    "guideOf": "{game} 攻略ガイド",
    "checkedBadge": "情報源確認済み",
    "allAreas": "このガイドの全エリア",
    "areaTitle": "{area} – {game} 攻略: アイテム、隠し要素、敵 | Quest Compendium",
    "areaDesc": "{game}「{area}」の攻略情報: アイテム、隠し要素、取り返しのつかない要素、敵の弱点。",
    "gameTitle": "{game} 攻略・解説 | Quest Compendium",
    "gameDesc": "アイテムチェックリスト、隠し要素、取り返しのつかない要素、敵の弱点を網羅した{game}のエリア別攻略ガイド。",
    "gameH1": "{game} 攻略ガイド",
    "gameIntro": "全エリアを順を追って掲載。アイテム、隠し要素、取り返しのつかない要素のチェックリスト付き。チェック状態はこのブラウザに保存されます。",
    "statAreas": "エリア",
    "statThings": "収集要素",
    "statMissables": "見逃し要素マーク済み",
    "statChecked": "情報源確認済みページ",
    "statAll": "すべて",
    "continue": "前回の続きから",
    "indexTitle": "ゲーム攻略ガイド一覧 | Quest Compendium",
    "indexDesc": "エリア別のアイテムチェックリスト、隠し要素、取り返しのつかない要素、敵の弱点を掲載したゲーム攻略ガイド。",
    "indexH1": "ゲーム攻略ガイド",
    "indexIntro": "{n}タイトルのアイテム、隠し要素、見逃し注意点、敵の弱点をエリア別チェックリストで掲載。",
    "indexMore": "英語版のガイドをもっと見る",
    "areasCount": "{n}エリア",
    "areasCountOne": "1エリア",
    "none": "最初のガイドを準備中です。"
  },
  ko: {
    "navGuides": "공략",
    "navGetApp": "앱 다운로드",
    "language": "언어",
    "footer": "이 가이드는 AI의 도움을 받아 작성되었습니다. 잘못된 내용이 있나요? {discord}에서 알려주세요. 게임 이름의 저작권은 해당 소유자에게 있으며, 이 사이트는 어떤 게임 배급사와도 관련이 없습니다.",
    "ctaTitle": "{game} 진행 중 막히셨나요?",
    "ctaBody": "Quest Compendium은 플레이 중인 화면을 인식합니다. 지금 있는 위치에 대해 바로 물어보고, 게임 화면 옆에 이 가이드를 띄워두고 플레이하세요.",
    "ctaButton": "플레이하며 실시간 도움 받기",
    "gotIt": "확인",
    "weakTo": "약점 속성",
    "stealDrop": "훔치기 / 드롭",
    "previous": "이전",
    "next": "다음",
    "dontMiss": "놓치기 쉬운 요소",
    "items": "아이템",
    "secrets": "비밀 요소",
    "enemies": "적 정보",
    "shops": "상점 및 NPC",
    "tips": "팁",
    "sourcesChecked": "교차 검증된 출처: {list}",
    "guideOf": "{game} 공략",
    "checkedBadge": "출처 검증 완료",
    "allAreas": "이 공략의 모든 구역",
    "areaTitle": "{area} – {game} 공략: 아이템, 비밀 요소, 적 정보 | Quest Compendium",
    "areaDesc": "{game} {area} 가이드: 아이템, 비밀 요소, 놓치기 쉬운 것들 및 적 약점.",
    "gameTitle": "{game} 공략 및 완벽 가이드 | Quest Compendium",
    "gameDesc": "구역별 {game} 공략: 아이템 체크리스트, 비밀 요소, 놓치기 쉬운 것들 및 적 약점 수록.",
    "gameH1": "{game} 공략",
    "gameIntro": "모든 구역을 순서대로 정리했으며 아이템, 비밀 요소, 놓치기 쉬운 것들의 체크리스트를 제공합니다. 체크 표시는 이 브라우저에 저장됩니다.",
    "statAreas": "개 구역",
    "statThings": "개 수집 요소",
    "statMissables": "개 놓치기 쉬운 요소",
    "statChecked": "개 페이지 교차 검증 완료",
    "statAll": "전체",
    "continue": "이어서 보기",
    "indexTitle": "게임 공략 및 완벽 가이드 | Quest Compendium",
    "indexDesc": "구역별 아이템 체크리스트, 비밀 요소, 놓치기 쉬운 것들 및 적 약점이 정리된 게임 공략입니다.",
    "indexH1": "게임 공략",
    "indexIntro": "{n}개 게임에 대한 구역별 아이템, 비밀 요소, 놓치기 쉬운 것들 체크리스트와 적 약점을 제공합니다.",
    "indexMore": "더 많은 영어 공략",
    "areasCount": "{n}개 구역",
    "areasCountOne": "1개 구역",
    "none": "첫 번째 공략을 곧 공개할 예정입니다."
  },
  pt: {
    "navGuides": "Guias",
    "navGetApp": "Baixar o app",
    "language": "Idioma",
    "footer": "Os guias são criados com ajuda de IA. Viu algum erro? Conta pra gente no {discord}. Os nomes dos jogos pertencem aos seus respectivos proprietários; este site não é afiliado a nenhuma publicadora.",
    "ctaTitle": "Empacou em alguma parte de {game}?",
    "ctaBody": "O Quest Compendium reconhece sua tela enquanto você joga: pergunte sobre exatamente onde você está e mantenha este guia aberto lado a lado com o jogo.",
    "ctaButton": "Receba ajuda ao vivo enquanto joga",
    "gotIt": "Entendi",
    "weakTo": "Fraqueza:",
    "stealDrop": "Roubo / drop",
    "previous": "Anterior",
    "next": "Próximo",
    "dontMiss": "Imperdível",
    "items": "Itens",
    "secrets": "Segredos",
    "enemies": "Inimigos",
    "shops": "Lojas e NPCs",
    "tips": "Dicas",
    "sourcesChecked": "Fontes verificadas: {list}",
    "guideOf": "Guia de {game}",
    "checkedBadge": "Conferido com fontes",
    "allAreas": "Todas as áreas deste guia",
    "areaTitle": "{area} – Guia de {game}: Itens, Segredos e Inimigos | Quest Compendium",
    "areaDesc": "Guia de {area} em {game}: itens, segredos, itens perdíveis e fraquezas de inimigos.",
    "gameTitle": "Guia e Detonado de {game} | Quest Compendium",
    "gameDesc": "Guia área por área de {game} com checklists de itens, segredos, itens perdíveis e fraquezas de inimigos.",
    "gameH1": "Guia de {game}",
    "gameIntro": "Todas as áreas em ordem, com checklists de itens, segredos e itens perdíveis. O progresso fica salvo neste navegador.",
    "statAreas": "áreas",
    "statThings": "coisas para achar",
    "statMissables": "itens perdíveis marcados",
    "statChecked": "páginas conferidas com fontes",
    "statAll": "Tudo",
    "continue": "Continuar de onde você parou",
    "indexTitle": "Guias de Jogos e Detonados | Quest Compendium",
    "indexDesc": "Guias de jogos com checklists de itens, segredos, itens perdíveis e fraquezas de inimigos, área por área.",
    "indexH1": "Guias de jogos",
    "indexIntro": "Checklists área por área de itens, segredos e itens perdíveis, além de fraquezas de inimigos, para {n} jogos.",
    "indexMore": "Mais guias em inglês",
    "areasCount": "{n} áreas",
    "areasCountOne": "1 área",
    "none": "Os primeiros guias chegam em breve."
  },
  ru: {
    "navGuides": "Гайды",
    "navGetApp": "Скачать приложение",
    "language": "Язык",
    "footer": "Гайды созданы с помощью ИИ. Заметили ошибку? Напишите нам в {discord}. Названия игр принадлежат их владельцам; сайт не связан с издателями.",
    "ctaTitle": "Застряли в {game}?",
    "ctaBody": "Quest Compendium видит ваш экран во время игры: задавайте вопросы о текущей локации и держите этот гайд под рукой прямо поверх игры.",
    "ctaButton": "Помощь в игре в реальном времени",
    "gotIt": "Понятно",
    "weakTo": "Уязвимость к",
    "stealDrop": "Кража / дроп",
    "previous": "Назад",
    "next": "Вперед",
    "dontMiss": "Не пропустите",
    "items": "Предметы",
    "secrets": "Секреты",
    "enemies": "Враги",
    "shops": "Торговцы и NPC",
    "tips": "Советы",
    "sourcesChecked": "Проверенные источники: {list}",
    "guideOf": "Гайд по {game}",
    "checkedBadge": "Сверено с источниками",
    "allAreas": "Все локации гайда",
    "areaTitle": "{area} — Гайд по {game}: предметы, секреты и враги | Quest Compendium",
    "areaDesc": "Гайд по локации {area} в {game}: предметы, секреты, пропускаемый контент и уязвимости врагов.",
    "gameTitle": "Гайд и прохождение {game} | Quest Compendium",
    "gameDesc": "Пошаговый гайд по {game} с чек-листами предметов, секретами, пропускаемым лутом и уязвимостями врагов.",
    "gameH1": "Гайд по {game}",
    "gameIntro": "Все локации по порядку, с чек-листами предметов, секретов и пропускаемых вещей. Отметки сохраняются в браузере.",
    "statAreas": "локаций",
    "statThings": "находок",
    "statMissables": "пропускаемых предметов",
    "statChecked": "страниц проверено по источникам",
    "statAll": "Все",
    "continue": "Продолжить с места остановки",
    "indexTitle": "Гайды и прохождения игр | Quest Compendium",
    "indexDesc": "Гайды по локациям с чек-листами предметов, секретами, пропускаемым лутом и уязвимостями врагов.",
    "indexH1": "Игровые гайды",
    "indexIntro": "Чек-листы локаций с предметами, секретами и пропускаемым контентом, а также уязвимости врагов для {n} игр.",
    "indexMore": "Больше гайдов на английском",
    "areasCount": "Локаций: {n}",
    "areasCountOne": "1 локация",
    "none": "Первые гайды уже готовятся к выходу."
  },
  zh: {
    "navGuides": "攻略",
    "navGetApp": "获取应用",
    "language": "语言",
    "footer": "攻略由 AI 辅助编写。发现错误？欢迎在 {discord} 上告诉我们。游戏名称归其所有者所有；本站不隶属于任何发行商。",
    "ctaTitle": "在《{game}》中卡关了？",
    "ctaBody": "Quest Compendium 可以在你游玩时读取屏幕：针对你当前的位置精准提问，攻略常驻游戏旁随时查看。",
    "ctaButton": "边玩边获取实时帮助",
    "gotIt": "知道了",
    "weakTo": "弱点属性",
    "stealDrop": "偷窃 / 掉落",
    "previous": "上一页",
    "next": "下一页",
    "dontMiss": "切勿错过",
    "items": "物品",
    "secrets": "秘密",
    "enemies": "敌人",
    "shops": "商店与 NPC",
    "tips": "提示",
    "sourcesChecked": "参考资料核对：{list}",
    "guideOf": "《{game}》攻略",
    "checkedBadge": "已核对资料来源",
    "allAreas": "本攻略包含的所有区域",
    "areaTitle": "{area} – 《{game}》攻略：物品、秘密与敌人 | Quest Compendium",
    "areaDesc": "《{game}》{area}区域攻略：物品、秘密、易错过内容和敌人弱点。",
    "gameTitle": "《{game}》完整攻略与流程指引 | Quest Compendium",
    "gameDesc": "分区域《{game}》全攻略，包含物品清单、秘密、易错过要素和敌人弱点。",
    "gameH1": "《{game}》攻略",
    "gameIntro": "按顺序整理的每个区域攻略，附带物品、秘密和易错过内容的核对清单。你的勾选进度会自动保存在当前浏览器中。",
    "statAreas": "个区域",
    "statThings": "处可探索内容",
    "statMissables": "处易错过标记",
    "statChecked": "页已核对资料",
    "statAll": "全部",
    "continue": "继续上次的进度",
    "indexTitle": "游戏攻略与流程指引 | Quest Compendium",
    "indexDesc": "分区域游戏攻略，包含物品清单、秘密、易错过要素及敌人弱点。",
    "indexH1": "游戏攻略",
    "indexIntro": "涵盖 {n} 款游戏的分区域核对清单，包含物品、秘密、易错过要素以及敌人弱点。",
    "indexMore": "更多英文攻略",
    "areasCount": "{n} 个区域",
    "areasCountOne": "1 个区域",
    "none": "首批攻略正在路上，敬请期待。"
  },
};
